### ISSUE TITLE
rename project

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/dicom-dataflow#2]
Hi @hurngchunlee, browsing through the list of github repos on donders-institute, I noticed the inconsistent naming. Would you mind renaming this one from DCCN-xxx to xxx? it being part of donders-institute should be sufficient that it is specific to our research site.  It also makes it more consistent with hcp-wiki and torque-monitor.

**Comment by hurngchunlee** [comment]
fixed.
